version: '3'
services:
  nodejs:
    build: .
    ports:
      - "5000:3000"
    container_name: nodejs_eve
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always

