version: '3'
services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    container_name: nodejsbase
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always

